project:
  type: website
  output-dir: docs

website:
  title: "50und.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/50und
format:
  html:
    theme: cosmo
    css: styles.css



